import { NextRequest, NextResponse } from 'next/server'
import { query, ApiResponse } from '@/lib/database/connection'
import { z } from 'zod'
import { AuthenticatedRequest, withPermission } from '@/middleware/auth'
import { CartService } from '@/lib/services/cart.services'

// ========== Types ==========
export interface ScannedProduct {
  barcode_id?: string 
  barcode: string
  scan_type: 'INDIVIDUAL_ITEM' | 'PRODUCT_LEVEL'
  product_id: string
  name: string
  model: string
  sku: string
  wholesale_quantity?: number 
  pricing: {
    cost_price: number
    wholesale_price?: number
    retail_price: number
    selling_price: number
  }
  inventory: {
    available_quantity: number
    is_low_stock: boolean
    total_batches?: number 
    fifo_next_batch?: {
      batch_id: string
      batch_number: string
      available_quantity: number
    }
  }
  item_details?: {
    item_id: string
    status: string
    condition: string
    warranty_expiry?: string
    location_branch: string
    purchased_at: string
    supplier_name?: string
  }
  batch_info?: {
    batch_id: string
    batch_number: string
    branch_quantity?: number
    branch_available?: number
  }
  requires_quantity_input: boolean
  max_quantity?: number
  warranty_period?: number
}

// ========== Validation Schema ==========
const scanRequestSchema = z.object({
  barcode: z.string().min(1, 'Barcode is required').trim()
})

// ========== Barcode Type Detection ==========
function detectBarcodeType(barcode: string): 'INDIVIDUAL_ITEM' | 'PRODUCT_LEVEL' | 'UNKNOWN' {
  // Individual item barcodes generated by system
  if (barcode.startsWith('ITEM')) return 'INDIVIDUAL_ITEM'
  
  // Product-level barcodes (internal or external)
  if (barcode.startsWith('PRO-') || 
      barcode.length === 13 || // EAN-13
      barcode.length === 12 || // UPC-A
      barcode.length === 8) {   // EAN-8
    return 'PRODUCT_LEVEL'
  }
  
  return 'UNKNOWN'
}

// ========== Enhanced Barcode Lookup (fallback for unknown formats) ==========
async function enhancedBarcodeSearch(
  barcode: string, 
  branchId: string
): Promise<ScannedProduct> {
  
  // Try to find the barcode in any barcode table
  const searchQuery = `
    -- Search in item_barcodes first
    SELECT 'INDIVIDUAL_ITEM' as source, code, product_id FROM item_barcodes 
    WHERE code = $1 AND is_active = true
    UNION ALL
    -- Search in product barcodes
    SELECT 'PRODUCT_LEVEL' as source, code, product_id FROM barcodes 
    WHERE code = $1
    LIMIT 1
  `
  const result = await query(searchQuery, [barcode])

  if (result.rows.length === 0) {
    throw new Error(`Barcode '${barcode}' not found in system`)
  }

  const found = result.rows[0]

  // Route to appropriate handler based on what we found
  if (found.source === 'INDIVIDUAL_ITEM') {
    return await CartService.handleIndividualItemScan(barcode, branchId)
  } else {
    return await CartService.handleProductLevelScan(barcode, branchId)
  }
}

// ========== Price Override Check ==========
async function checkPriceOverrides(
  productId: string, 
  branchId: string, 
  basePrice: number
): Promise<number> {
  
  const overrideQuery = `
    SELECT override_price
    FROM price_overrides
    WHERE product_id = $1 
      AND branch_id = $2
      AND is_active = true
      AND valid_from <= NOW()
      AND (valid_until IS NULL OR valid_until >= NOW())
    ORDER BY valid_from DESC
    LIMIT 1
  `

  const result = await query(overrideQuery, [productId, branchId])

  if (result.rows.length > 0) {
    return parseFloat(result.rows[0].override_price)
  }

  return basePrice
}

// ========== Main API Handler ==========
export async function POST(request: NextRequest) {
  return withPermission('create_product')(async (authedReq: AuthenticatedRequest) => {
    try {
      const body = await authedReq.json();
      const { user: userDetails } = authedReq.user;
      
      const validation = scanRequestSchema.safeParse(body);
      
      if (!validation.success) {
        return NextResponse.json({
          success: false,
          data: null,
          message: 'Validation failed',
          errors: validation.error.errors.map(err => ({
            path: err.path.join('.'),
            message: err.message
          })),
          timestamp: new Date().toISOString()
        }, { status: 400 })
      }

      const { barcode } = validation.data

      // Detect barcode type
      let barcodeType = detectBarcodeType(barcode)
      let scannedProduct: ScannedProduct

      try {
        // Route to appropriate handler
        if (barcodeType === 'INDIVIDUAL_ITEM') {
          scannedProduct = await CartService.handleIndividualItemScan(barcode, userDetails.branch_id)
        } else if (barcodeType === 'PRODUCT_LEVEL') {
          scannedProduct = await CartService.handleProductLevelScan(barcode, userDetails.branch_id)
        } else {
          // Try enhanced search for unknown formats
          console.log(`⚠️ Unknown barcode format, trying enhanced search: ${barcode}`)
          scannedProduct = await enhancedBarcodeSearch(barcode, userDetails.branch_id)
        }

        // Check for price overrides
        const overriddenPrice = await checkPriceOverrides(
          scannedProduct.product_id, 
          userDetails.branch_id, 
          scannedProduct.pricing.retail_price
        )

        if (overriddenPrice !== scannedProduct.pricing.retail_price) {
          scannedProduct.pricing.selling_price = overriddenPrice
          console.log(`💰 Price override applied: ${scannedProduct.pricing.retail_price} → ${overriddenPrice}`)
        }

      } catch (error: any) {
        console.error(`❌ Barcode scan error: ${error.message}`)
        
        return NextResponse.json({
          success: false,
          data: null,
          message: error.message,
          errors: [{
            code: barcodeType === 'INDIVIDUAL_ITEM' ? 'ITEM_NOT_AVAILABLE' : 'PRODUCT_NOT_FOUND',
            message: error.message,
            barcode,
            branch_id: userDetails.branch_id
          }],
          timestamp: new Date().toISOString()
        }, { status: 404 })
      }

      // Success response with product data for frontend
      console.log(`✅ Successfully scanned: ${scannedProduct.name} (${scannedProduct.scan_type})`)
      
      return NextResponse.json({
        success: true,
        data: scannedProduct,
        message: `Product scanned successfully - ${scannedProduct.requires_quantity_input ? 'enter quantity' : 'ready to add to cart'}`,
        metadata: {
          scan_type: scannedProduct.scan_type,
          branch_id: userDetails.branch_id,
          has_price_override: scannedProduct.pricing.selling_price !== scannedProduct.pricing.retail_price,
          inventory_status: scannedProduct.inventory.is_low_stock ? 'LOW_STOCK' : 'NORMAL'
        },
        timestamp: new Date().toISOString()
      })

    } catch (error: any) {
      console.error('💥 Error in barcode scan API:', error)
      
      return NextResponse.json<ApiResponse>({
        success: false,
        data: null,
        message: 'Internal server error',
        errors: [{ 
          message: 'An unexpected error occurred while scanning barcode',
          details: process.env.NODE_ENV === 'development' ? error.message : undefined
        }],
        timestamp: new Date().toISOString()
      }, { status: 500 })
    }
  })(request)
}