import { NextRequest, NextResponse } from 'next/server'
import { query, ApiResponse } from '@/lib/database/connection'
import { z } from 'zod'
import { AuthenticatedRequest, withPermission } from '@/middleware/auth'

// ========== Types ==========
export interface ScannedProduct {
  barcode_id?: string // For individual items, this is the item barcode ID
  barcode: string
  scan_type: 'INDIVIDUAL_ITEM' | 'PRODUCT_LEVEL'
  product_id: string
  name: string
  model: string
  sku: string
  brand?: {
    name: string
    code: string
  }
  category?: {
    category: string
    subcategory: string
  }
  pricing: {
    cost_price: number
    wholesale_price?: number
    retail_price: number
    selling_price: number
  }
  inventory: {
    available_quantity: number
    is_low_stock: boolean
  }
  // For individual items
  item_details?: {
    item_id: string
    status: string
    condition: string
    warranty_expiry?: string
    location_branch: string
    purchased_at: string
    supplier_name?: string
  }
  batch_info?: {
    batch_id: string
    batch_number: string
    expiry_date?: string
    branch_quantity?: number
    branch_available?: number
  }
  // For product-level items
  requires_quantity_input: boolean
  max_quantity?: number
  warranty_period?: number
}

// ========== Validation Schema ==========
const scanRequestSchema = z.object({
  barcode: z.string().min(1, 'Barcode is required').trim()
})

// ========== Barcode Type Detection ==========
function detectBarcodeType(barcode: string): 'INDIVIDUAL_ITEM' | 'PRODUCT_LEVEL' | 'UNKNOWN' {
  // Individual item barcodes generated by system
  if (barcode.startsWith('ITEM')) return 'INDIVIDUAL_ITEM'
  
  // Product-level barcodes (internal or external)
  if (barcode.startsWith('PRO_') || 
      barcode.startsWith('INT_') || 
      barcode.length === 13 || // EAN-13
      barcode.length === 12 || // UPC-A
      barcode.length === 8) {   // EAN-8
    return 'PRODUCT_LEVEL'
  }
  
  return 'UNKNOWN'
}

// ========== Individual Item Scan Handler ==========
async function handleIndividualItemScan(
  barcode: string, 
  branchId: string
): Promise<ScannedProduct> {
  
  const itemQuery = `
    SELECT 
      ib.id as item_id,
      ib.code as barcode,
      ib.status,
      ib.condition,
      ib.warranty_expiry,
      ib.location_branch,
      ib.purchased_at,
      ib.purchase_cost,
      pb.id as batch_id,
      pb.batch_number,
      pb.cost_price,
      pb.wholesale_price,
      pb.retail_price,
      pb.expiry_date,
      ib.product_id,
      p.name as product_name,
      p.model,
      p.sku,
      p.warranty_period,
      b.name as brand_name,
      b.code as brand_code,
      sc.name as subcategory_name,
      c.name as category_name,
      s.name as supplier_name,
      s.code as supplier_code,
      -- Branch inventory details
      bi.total_quantity,
      bi.reserved_quantity,
      (bi.total_quantity - bi.reserved_quantity) as available_quantity,
      bi.low_stock_threshold,
      -- Batch availability in this branch
      bii.quantity as batch_quantity_in_branch,
      bii.reserved_quantity as batch_reserved_quantity,
      (bii.quantity - bii.reserved_quantity) as batch_available_quantity,
      -- Current pricing
      pb.cost_price as current_cost_price,
      pb.wholesale_price as current_wholesale_price,
      pb.retail_price as current_retail_price
    FROM item_barcodes ib
    JOIN purchase_batches pb ON ib.purchase_batch_id = pb.id
    JOIN products p ON ib.product_id = p.id
    LEFT JOIN suppliers s ON ib.supplier_id = s.id
    LEFT JOIN brands b ON p.brand_id = b.id
    LEFT JOIN subcategories sc ON p.subcategory_id = sc.id
    LEFT JOIN categories c ON sc.category_id = c.id
    LEFT JOIN product_current_prices pcp ON p.id = pcp.product_id
    -- Branch inventory check
    LEFT JOIN branch_inventory bi ON p.id = bi.product_id AND bi.branch_id = $2
    -- Batch availability in this branch
    LEFT JOIN branch_inventory_items bii ON pb.id = bii.purchase_batch_id 
                                          AND bii.branch_inventory_id = bi.id
                                          AND bii.is_active = true
    WHERE ib.code = $1 AND ib.is_active = true
  `

  const result = await query(itemQuery, [barcode, branchId])

  if (result.rows.length === 0) {
    throw new Error(`Individual item barcode '${barcode}' not found in system`)
  }

  const item = result.rows[0]

  // Check if item barcode is available for sale
  if (item.status !== 'AVAILABLE') {
    throw new Error(`Item is ${item.status.toLowerCase()} and cannot be sold`)
  }

  // Check if item condition is sellable
  if (['DAMAGED', 'EXPIRED', 'DEFECTIVE'].includes(item.condition)) {
    throw new Error(`Item condition is ${item.condition.toLowerCase()} and cannot be sold`)
  }

  // Check if item is in the correct branch
  if (item.location_branch !== branchId) {
    throw new Error(`Item is located in a different branch. Current location: ${item.location_branch}`)
  }

  // Check if product exists in this branch inventory
  if (item.total_quantity === null || item.total_quantity === undefined) {
    throw new Error(`Product '${item.product_name}' is not available in this branch`)
  }

  // Check if overall product has stock in this branch
  if (!item.available_quantity || item.available_quantity <= 0) {
    throw new Error(`Product '${item.product_name}' is out of stock in this branch`)
  }

  // Check if the specific batch exists in this branch
  if (item.batch_quantity_in_branch === null || item.batch_quantity_in_branch === undefined) {
    throw new Error(`This specific item batch is not located in this branch`)
  }

  // Check if the batch has available quantity in this branch
  if (!item.batch_available_quantity || item.batch_available_quantity <= 0) {
    throw new Error(`This item's batch is out of stock in this branch`)
  }

  // Use current pricing if available, otherwise fall back to batch pricing
  const costPrice = item.current_cost_price || item.cost_price || item.purchase_cost
  const wholesalePrice = item.current_wholesale_price || item.wholesale_price
  const retailPrice = item.current_retail_price || item.retail_price

  return {
    barcode_id: item.item_id,
    barcode: item.barcode,
    scan_type: 'INDIVIDUAL_ITEM',
    product_id: item.product_id,
    name: item.product_name,
    model: item.model,
    sku: item.sku,
    brand: item.brand_name ? {
      name: item.brand_name,
      code: item.brand_code
    } : undefined,
    category: item.category_name ? {
      category: item.category_name,
      subcategory: item.subcategory_name
    } : undefined,
    pricing: {
      cost_price: parseFloat(costPrice || '0'),
      wholesale_price: wholesalePrice ? parseFloat(wholesalePrice) : undefined,
      retail_price: parseFloat(retailPrice || '0'),
      selling_price: parseFloat(retailPrice || '0')
    },
    inventory: {
      available_quantity: item.available_quantity,
      is_low_stock: item.available_quantity <= (item.low_stock_threshold || 0)
    },
    item_details: {
      item_id: item.item_id,
      status: item.status,
      condition: item.condition,
      warranty_expiry: item.warranty_expiry,
      location_branch: item.location_branch,
      purchased_at: item.purchased_at,
      supplier_name: item.supplier_name
    },
    batch_info: {
      batch_id: item.batch_id,
      batch_number: item.batch_number,
      expiry_date: item.expiry_date,
      branch_quantity: item.batch_quantity_in_branch,
      branch_available: item.batch_available_quantity
    },
    requires_quantity_input: false, // Always 1 for individual items
    warranty_period: item.warranty_period
  }
}

// ========== Updated Product Level Scan Handler ==========
async function handleProductLevelScan(
  barcode: string, 
  branchId: string
): Promise<ScannedProduct> {
  
  const productQuery = `
    SELECT 
      bc.id as barcode_id,
      bc.code as barcode,
      bc.type,
      p.id as product_id,
      p.name as product_name,
      p.model,
      p.sku,
      p.warranty_period,
      b.name as brand_name,
      b.code as brand_code,
      sc.name as subcategory_name,
      c.name as category_name,
      -- Current pricing
      pcp.cost_price,
      pcp.wholesale_price,
      pcp.retail_price,
      pcp.last_updated as price_last_updated,
      -- Branch-specific inventory
      bi.total_quantity,
      bi.reserved_quantity,
      (bi.total_quantity - bi.reserved_quantity) as available_quantity,
      bi.low_stock_threshold,
      bi.average_cost_price,
      -- Available batches with FIFO ordering
      json_agg(
        json_build_object(
          'batch_id', pb.id,
          'batch_number', pb.batch_number,
          'quantity', (bii.quantity - bii.reserved_quantity),
          'cost_price', pb.cost_price,
          'wholesale_price', pb.wholesale_price,
          'retail_price', pb.retail_price,
          'expiry_date', pb.expiry_date,
          'received_date', pb.received_date
        ) ORDER BY 
          COALESCE(pb.fifo_sequence, 999999) ASC,
          pb.received_date ASC NULLS LAST,
          pb.expiry_date ASC NULLS LAST,
          pb.created_at ASC
      ) FILTER (
        WHERE bii.quantity > bii.reserved_quantity 
          AND bii.is_active = true 
          AND pb.is_active = true
          AND (pb.expiry_date IS NULL OR pb.expiry_date > CURRENT_DATE)
      ) as batches
    FROM barcodes bc
    JOIN products p ON bc.product_id = p.id
    LEFT JOIN brands b ON p.brand_id = b.id
    LEFT JOIN subcategories sc ON p.subcategory_id = sc.id
    LEFT JOIN categories c ON sc.category_id = c.id
    LEFT JOIN product_current_prices pcp ON p.id = pcp.product_id
    LEFT JOIN branch_inventory bi ON p.id = bi.product_id AND bi.branch_id = $2
    LEFT JOIN branch_inventory_items bii ON bi.id = bii.branch_inventory_id 
                                          AND bii.is_active = true
    LEFT JOIN purchase_batches pb ON bii.purchase_batch_id = pb.id
                                   AND pb.is_active = true
    WHERE bc.code = $1 AND bc.is_active = true AND p.is_active = true
    GROUP BY bc.id, bc.code, bc.type, p.id, p.name, p.model, p.sku, p.warranty_period,
             b.name, b.code, sc.name, c.name, pcp.cost_price, pcp.wholesale_price, 
             pcp.retail_price, pcp.last_updated, bi.total_quantity, bi.reserved_quantity, 
             bi.low_stock_threshold, bi.average_cost_price
  `

  const result = await query(productQuery, [barcode, branchId])

  if (result.rows.length === 0) {
    throw new Error(`Product barcode '${barcode}' not found in system`)
  }

  const product = result.rows[0]

  // Check if product exists in this branch
  if (product.total_quantity === null || product.total_quantity === undefined) {
    throw new Error(`Product '${product.product_name}' is not available in this branch`)
  }

  // Check if product has stock in this branch
  if (!product.available_quantity || product.available_quantity <= 0) {
    throw new Error(`Product '${product.product_name}' is out of stock in this branch`)
  }

  // Get batches (already ordered by FIFO)
  const batches = product.batches || []

  // Check if there are available batches
  if (batches.length === 0) {
    throw new Error(`No available batches for product '${product.product_name}' in this branch`)
  }

  // Use current pricing or fallback to average cost
  const costPrice = product.cost_price || product.average_cost_price || 0
  const wholesalePrice = product.wholesale_price
  const retailPrice = product.retail_price || 0

  return {
    barcode: product.barcode,
    scan_type: 'PRODUCT_LEVEL',
    product_id: product.product_id,
    name: product.product_name,
    model: product.model,
    sku: product.sku,
    brand: product.brand_name ? {
      name: product.brand_name,
      code: product.brand_code
    } : undefined,
    category: product.category_name ? {
      category: product.category_name,
      subcategory: product.subcategory_name
    } : undefined,
    pricing: {
      cost_price: parseFloat(costPrice.toString()),
      wholesale_price: wholesalePrice ? parseFloat(wholesalePrice.toString()) : undefined,
      retail_price: parseFloat(retailPrice.toString()),
      selling_price: parseFloat(retailPrice.toString())
    },
    inventory: {
      available_quantity: product.available_quantity || 0,
      is_low_stock: (product.available_quantity || 0) <= (product.low_stock_threshold || 0)
    },
    batch_info: batches.map((batch: any) => ({
      batch_id: batch.batch_id,
      batch_number: batch.batch_number,
      quantity: batch.quantity,
      cost_price: parseFloat(batch.cost_price || '0'),
      wholesale_price: batch.wholesale_price ? parseFloat(batch.wholesale_price) : undefined,
      retail_price: parseFloat(batch.retail_price || '0'),
      expiry_date: batch.expiry_date,
      received_date: batch.received_date
    })),
    requires_quantity_input: true,
    max_quantity: product.available_quantity || 0,
    warranty_period: product.warranty_period
  }
}
// ========== Enhanced Barcode Lookup (fallback for unknown formats) ==========
async function enhancedBarcodeSearch(
  barcode: string, 
  branchId: string
): Promise<ScannedProduct> {
  
  // Try to find the barcode in any barcode table
  const searchQuery = `
    -- Search in item_barcodes first
    SELECT 'INDIVIDUAL_ITEM' as source, code, product_id FROM item_barcodes 
    WHERE code = $1 AND is_active = true
    UNION ALL
    -- Search in product barcodes
    SELECT 'PRODUCT_LEVEL' as source, code, product_id FROM barcodes 
    WHERE code = $1 AND is_active = true
    LIMIT 1
  `

  const result = await query(searchQuery, [barcode])

  if (result.rows.length === 0) {
    throw new Error(`Barcode '${barcode}' not found in system`)
  }

  const found = result.rows[0]

  // Route to appropriate handler based on what we found
  if (found.source === 'INDIVIDUAL_ITEM') {
    return await handleIndividualItemScan(barcode, branchId)
  } else {
    return await handleProductLevelScan(barcode, branchId)
  }
}

// ========== Price Override Check ==========
async function checkPriceOverrides(
  productId: string, 
  branchId: string, 
  basePrice: number
): Promise<number> {
  
  const overrideQuery = `
    SELECT override_price
    FROM price_overrides
    WHERE product_id = $1 
      AND branch_id = $2
      AND is_active = true
      AND valid_from <= NOW()
      AND (valid_until IS NULL OR valid_until >= NOW())
    ORDER BY valid_from DESC
    LIMIT 1
  `

  const result = await query(overrideQuery, [productId, branchId])

  if (result.rows.length > 0) {
    return parseFloat(result.rows[0].override_price)
  }

  return basePrice
}

// ========== Main API Handler ==========
export async function POST(request: NextRequest) {
  return withPermission('create_product')(async (authedReq: AuthenticatedRequest) => {
    try {
      const body = await authedReq.json()
      const { user: userDetails } = authedReq.user

      // Validate request
      const validation = scanRequestSchema.safeParse(body)
      if (!validation.success) {
        return NextResponse.json({
          success: false,
          data: null,
          message: 'Validation failed',
          errors: validation.error.errors.map(err => ({
            path: err.path.join('.'),
            message: err.message
          })),
          timestamp: new Date().toISOString()
        }, { status: 400 })
      }

      const { barcode } = validation.data

      console.log(`🔍 Scanning barcode: ${barcode} for branch: ${userDetails.branch_id}`)

      // Detect barcode type
      let barcodeType = detectBarcodeType(barcode)
      let scannedProduct: ScannedProduct

      try {
        // Route to appropriate handler
        if (barcodeType === 'INDIVIDUAL_ITEM') {
          scannedProduct = await handleIndividualItemScan(barcode, userDetails.branch_id)
        } else if (barcodeType === 'PRODUCT_LEVEL') {
          scannedProduct = await handleProductLevelScan(barcode, userDetails.branch_id)
        } else {
          // Try enhanced search for unknown formats
          console.log(`⚠️ Unknown barcode format, trying enhanced search: ${barcode}`)
          scannedProduct = await enhancedBarcodeSearch(barcode, userDetails.branch_id)
        }

        // Check for price overrides
        const overriddenPrice = await checkPriceOverrides(
          scannedProduct.product_id, 
          userDetails.branch_id, 
          scannedProduct.pricing.retail_price
        )

        if (overriddenPrice !== scannedProduct.pricing.retail_price) {
          scannedProduct.pricing.selling_price = overriddenPrice
          console.log(`💰 Price override applied: ${scannedProduct.pricing.retail_price} → ${overriddenPrice}`)
        }

      } catch (error: any) {
        console.error(`❌ Barcode scan error: ${error.message}`)
        
        return NextResponse.json({
          success: false,
          data: null,
          message: error.message,
          errors: [{
            code: barcodeType === 'INDIVIDUAL_ITEM' ? 'ITEM_NOT_AVAILABLE' : 'PRODUCT_NOT_FOUND',
            message: error.message,
            barcode,
            branch_id: userDetails.branch_id
          }],
          timestamp: new Date().toISOString()
        }, { status: 404 })
      }

      // Success response with product data for frontend
      console.log(`✅ Successfully scanned: ${scannedProduct.name} (${scannedProduct.scan_type})`)
      
      return NextResponse.json({
        success: true,
        data: scannedProduct,
        message: `Product scanned successfully - ${scannedProduct.requires_quantity_input ? 'enter quantity' : 'ready to add to cart'}`,
        metadata: {
          scan_type: scannedProduct.scan_type,
          branch_id: userDetails.branch_id,
          has_price_override: scannedProduct.pricing.selling_price !== scannedProduct.pricing.retail_price,
          inventory_status: scannedProduct.inventory.is_low_stock ? 'LOW_STOCK' : 'NORMAL'
        },
        timestamp: new Date().toISOString()
      })

    } catch (error: any) {
      console.error('💥 Error in barcode scan API:', error)
      
      return NextResponse.json<ApiResponse>({
        success: false,
        data: null,
        message: 'Internal server error',
        errors: [{ 
          message: 'An unexpected error occurred while scanning barcode',
          details: process.env.NODE_ENV === 'development' ? error.message : undefined
        }],
        timestamp: new Date().toISOString()
      }, { status: 500 })
    }
  })(request)
}

// ========== GET Handler for Barcode Information ==========
export async function GET(request: NextRequest) {
  return withPermission('view_product')(async (authedReq: AuthenticatedRequest) => {
    try {
      const { searchParams } = new URL(request.url)
      const barcode = searchParams.get('barcode')
      const { user: userDetails } = authedReq.user

      if (!barcode) {
        return NextResponse.json({
          success: false,
          data: null,
          message: 'Barcode parameter is required',
          timestamp: new Date().toISOString()
        }, { status: 400 })
      }

      // Get barcode information without availability checks
      const infoQuery = `
        SELECT 
          'INDIVIDUAL_ITEM' as type,
          ib.id,
          ib.code,
          ib.status,
          ib.condition,
          ib.location_branch,
          p.name as product_name,
          p.sku,
          b.name as branch_name
        FROM item_barcodes ib
        JOIN products p ON ib.product_id = p.id
        LEFT JOIN branches b ON ib.location_branch = b.id
        WHERE ib.code = $1 AND ib.is_active = true
        
        UNION ALL
        
        SELECT 
          'PRODUCT_LEVEL' as type,
          bc.code,
          'N/A' as status,
          'N/A' as condition,
          'ALL_BRANCHES' as location_branch,
          p.name as product_name,
          p.sku,
          'Multiple' as branch_name
        FROM barcodes bc
        JOIN products p ON bc.product_id = p.id
        WHERE bc.code = $1 AND bc.is_active = true
      `

      const result = await query(infoQuery, [barcode])

      if (result.rows.length === 0) {
        return NextResponse.json({
          success: false,
          data: null,
          message: 'Barcode not found',
          timestamp: new Date().toISOString()
        }, { status: 404 })
      }

      return NextResponse.json({
        success: true,
        data: result.rows[0],
        message: 'Barcode information retrieved successfully',
        timestamp: new Date().toISOString()
      })

    } catch (error: any) {
      console.error('Error in barcode info API:', error)
      
      return NextResponse.json({
        success: false,
        data: null,
        message: 'Internal server error',
        errors: [{ message: error.message }],
        timestamp: new Date().toISOString()
      }, { status: 500 })
    }
  })(request)
}